### ISSUE TITLE
[Insight] The Symfony Dependency Injection Container should not be passed as an argument - in Decoda/Hook/EmoticonHook.php, line 56

### ISSUE THREAD

**Issue by helios-ag** [helios-ag/FMBbCodeBundle#122]
**[in Decoda/Hook/EmoticonHook.php, line 56](https://github.com/helios-ag/FMBbCodeBundle/blob/7208401df22c0ca3eb0de047a0f52fb1af2b3057/Decoda/Hook/EmoticonHook.php#L56)**

> A Symfony dependency injection container has been found as an argument.

``` php
     *
     * @param LoaderInterface $loader   A LoaderInterface instance
     * @param mixed           $resource The main resource to load
     * @param array           $options  An array of options
     */
    public function __construct(LoaderInterface $loader, ContainerInterface $container, array $options = array())
    {
        $this->loader    = $loader;
        $this->container = $container;
        $this->setOptions($options);

```

---

_Posted from [SensioLabsInsight](https://insight.sensiolabs.com/projects/f355c58b-f9b6-482c-8d2d-d1bc8791c9e5/analyses/30?status=violations)_

**Comment by alquerci** [comment]
There is a good reason to inject the container because we need them to replace placeholders [[ref](https://github.com/helios-ag/FMBbCodeBundle/blob/7208401df22c0ca3eb0de047a0f52fb1af2b3057/Decoda/Hook/EmoticonHook.php#L285)] like on the `Symfony\Bundle\FrameworkBundle\Routing\Router` [[ref](https://github.com/symfony/symfony/blob/e756135f649314f810cf9370d0e0bf8d261740ed/src/Symfony/Bundle/FrameworkBundle/Routing/Router.php#L76)].

**Comment by helios-ag** [comment]
Another approach is to inject parameters directly, so we can process them inside hook. Yaml file can be read by Yaml\Parser. What is your opinion, @alquerci ?

**Comment by alquerci** [comment]
> inject parameters directly

Indeed here we just need of all container parameters but it is not possible to inject all of them.

> Yaml file can be read by Yaml\Parser.

I do not understand you idea with this sentence. A parser can only parse and do not anything else.

This is the exception to the rule of not injecting the container.

The behind feature is a way to use all container parameters to avoid duplicate configuration like shown on the README:
```yaml
# path/to/emoticons.yml
imports:
  - { resource: path/to/another/emoticons.yml }

emoticons:
  my_emoticon:
    url:   # Default: %fm_bbcode.emoticon.path%/my_emoticon.png
    html:  # Default: <img src="%fm_bbcode.emoticon.path%/my_emoticon.png" alt="" >
    xHtml: # Default: <img src="%fm_bbcode.emoticon.path%/my_emoticon.png" alt="" />
    smilies:
      - ":my_emoticon:"
```

In order to keep back compatibility we cannot remove this feature.

But it's possible that is only useful to resolve the `fm_bbcode.emoticon` parameter namespace. In that case we can inject only all needed parameters to resolve them for the next major version (it is a regression).
