### ISSUE TITLE
Quote and Code tags do not seem to work.

### ISSUE THREAD

**Issue by reecefowell** [helios-ag/FMBbCodeBundle#14]
Is there an issue with using code and quote tags, or some kind of special use case?

Same for smilies, i see it in the readme, but its not really documented. 

I added it to my white list. But it just spits out the tag as it was put in.

``` yml
# app/config/config.yml
fm_bbcode:
    filter_sets:
        forum_post_filter:
            locale: en
            xhtml: true
            filters: [ default ]
            whitelist: [ default, b, u, i, list, quote, code, text, url, email, image, video ]
```

``` twig
{{ post.getBody | bbcode_filter('forum_post_filter') }}
```

Input examples.

code

``` UBB
[code]foo[/code]

[CODE]foo[/CODE]

[CODE=C++]#include std:io[/CODE]
```

quote

``` UBB
[QUOTE=Reece] blah blah blah blah...[/QUOTE]

[QUOTE]foo and bar[/QUOTE]

[quote]foo bar[/quote]
```

Comes out same as it went in. Bold, Italics and Underline seem to be working just fine though.

Otherwise, if everything works fine, then is there a means to define your own tags and its counter part html?
