### ISSUE TITLE
Locale configuration

### ISSUE THREAD

**Issue by jcrombez** [helios-ag/FMBbCodeBundle#33]
By default, the locale configuration is set to "ru-ru", i had to set it to "fr-fr" in the configuration to get it working in my language.

First, "xx-xx" is a weird format for a locale.

Second, can't the bundle just use the current SF locale ?

My best workaround for now is : 

``` yaml
fm_bbcode:
    filter_sets:
        forum:
            locale: %locale%-%locale%
```

But i think the bundle should be able to do that automatically.
