### ISSUE TITLE
[url] bbcode requires quotes to be filtered

### ISSUE THREAD

**Issue by dave128** [helios-ag/FMBbCodeBundle#95]
It seems that the URL filter requires the bbcode to use quotes to mark it as a URL correctly.

For example:

[url=www.google.com]www.google.com[/url] - does not work
[url="www.google.com"]www.google.com[/url] - works!

Per all bbcode standards I have seen, the url bbcode does not require quotations.

http://www.bbcode.org/examples/?id=9

Is there a way to use the more standard url bbcode syntax or am I doing something wrong?

EDIT:  The reason I need this is that I am doing a forum migration from an old platform to symfony and all of the old post use the non-quoted url bbcode.

Thanks!

**Comment by helios-ag** [comment]
Hi @dave128, disable "strict" option, that requires double quotes for attributes
```yaml
fm_bbcode:
  filter_sets:
    my_default_filter:
      strict: false #
```

**Comment by dave128** [comment]
Ah okay I swear I tried that before and it didn't work.  I didn't have the best test case though because many of the links I am migrating use the [b] tag inside the url which causes the text to be bolded but doesn't apply the link.

Ex: [url=www.google.com][b]Google[/b][/url]
Ex: [b][url=www.google.com]Google[/url][/b]

Both bbcodes return just the bold text.

Should that be supported or is there any other setting that needs to be added to support a nested bbcode?

Thank you for the quick response I really appreciate it!

**Comment by helios-ag** [comment]
Thats a strange behavior, here is mine config for bundle:
```yaml
fm_bbcode:
  filter_sets:
    my_default_filter:
      strict: false # if you want to parse attr values without quotes
      locale: en
      xhtml: false
      filters: [ default, block, code, email, image, list, url ]
```

and test string:
```twig
    {{'[url=www.google.ru]Google[/url]
    [url=www.google.com][b]Google[/b][/url]
    [b][url=www.google.com]Google[/url][/b]
'|bbcode_filter('my_default_filter') }}
```

which returns the following:
```html
<a href="http://www.google.ru">Google</a><br>    <a href="http://www.google.com"><b>Google</b></a><br>    <b><a href="http://www.google.com">Google</a></b>
```
